### ISSUE TITLE
大佬你这个脚本是怎么用的

### ISSUE THREAD

**Issue by shijinliang** [Suyu6/sub#1]

**Comment by Suyu6** [comment]
没明白你说的什么意思,指的什么

**Comment by shijinliang** [comment]
> 没明白你说的什么意思,指的什么

我看[all_base.tpl](https://github.com/Suyu6/sub/blob/master/base/all_base.tpl)里面有很多自动化脚本，这一套可以一次性部署完，全部跑起来吗？

**Comment by Suyu6** [comment]
> 我看[all_base.tpl](https://github.com/Suyu6/sub/blob/master/base/all_base.tpl)里面有很多自动化脚本，这一套可以一次性部署完，全部跑起来吗？
大部分应该是可以的,你自测下吧,而且是手机用的,你总是要抓cookie的

**Comment by shijinliang** [comment]
> > 我看[all_base.tpl](https://github.com/Suyu6/sub/blob/master/base/all_base.tpl)里面有很多自动化脚本，这一套可以一次性部署完，全部跑起来吗？
> > 大部分应该是可以的,你自测下吧,而且是手机用的,你总是要抓cookie的

哦哦，我以为这个是可以快速部署的呢，哈哈，谢谢大佬
